create table if not exists public.ef_product_licenses (
  id uuid primary key default gen_random_uuid(),
  product text not null check (product in ('agent-reliability')),
  license_key_hash text not null unique,
  status text not null default 'active' check (status in ('active','revoked')),
  perpetual_use boolean not null default true,
  updates_through timestamptz,
  max_activations integer not null default 3 check (max_activations > 0),
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);

create table if not exists public.ef_license_activations (
  id uuid primary key default gen_random_uuid(),
  license_id uuid not null references public.ef_product_licenses(id) on delete cascade,
  device_id_hash text not null,
  first_activated_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  user_agent text,
  unique (license_id, device_id_hash)
);

create table if not exists public.ef_license_activation_attempts (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  attempted_at timestamptz not null default now(),
  success boolean not null
);

alter table public.ef_product_licenses enable row level security;
alter table public.ef_license_activations enable row level security;
alter table public.ef_license_activation_attempts enable row level security;

create index if not exists ef_license_attempts_ip_time_idx
  on public.ef_license_activation_attempts(ip_hash, attempted_at desc);

create or replace function public.ef_activate_license(
  p_product text,
  p_license_key_hash text,
  p_device_id_hash text,
  p_user_agent text default null
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  lic public.ef_product_licenses%rowtype;
  activation_count integer;
begin
  select * into lic
  from public.ef_product_licenses
  where product = p_product
    and license_key_hash = p_license_key_hash
  for update;

  if not found then return jsonb_build_object('ok', false, 'code', 'LICENSE_INVALID'); end if;
  if lic.status <> 'active' then return jsonb_build_object('ok', false, 'code', 'LICENSE_REVOKED'); end if;

  if exists (
    select 1 from public.ef_license_activations
    where license_id = lic.id and device_id_hash = p_device_id_hash
  ) then
    update public.ef_license_activations
      set last_seen_at = now(), user_agent = left(coalesce(p_user_agent,''), 512)
    where license_id = lic.id and device_id_hash = p_device_id_hash;
  else
    select count(*) into activation_count from public.ef_license_activations where license_id = lic.id;
    if activation_count >= lic.max_activations then
      return jsonb_build_object('ok', false, 'code', 'ACTIVATION_LIMIT_REACHED');
    end if;
    insert into public.ef_license_activations(license_id, device_id_hash, user_agent)
    values (lic.id, p_device_id_hash, left(coalesce(p_user_agent,''), 512));
  end if;

  return jsonb_build_object(
    'ok', true,
    'entitlement', jsonb_build_object(
      'product', lic.product,
      'perpetualUse', lic.perpetual_use,
      'updatesThrough', lic.updates_through,
      'status', upper(lic.status)
    )
  );
end;
$$;

revoke all on function public.ef_activate_license(text,text,text,text) from public, anon, authenticated;
grant execute on function public.ef_activate_license(text,text,text,text) to service_role;
